- type: replace
  path: /vm_extensions/name=rabbitmq-lb?
  value:
    name: rabbitmq-lb
    cloud_properties:
      elbs:
      - ((rabbitmq_lb_name))
      security_groups:
      - ((rabbitmq_security_group))